version: "3.7"
services:
  huboxt-landing:
    build:
      context: .
      dockerfile: Dockerfile
    image: huboxt-landing
    container_name: huboxt-landing
    restart: unless-stopped
    environment:
      NODE_ENV: production

    logging:
      driver: "json-file"
      options:
        max-size: "256m"
        max-file: "10"

  nginx:
    image: nginx:latest
    restart: always
    environment:
      VIRTUAL_HOST: ${DOMAIN_NAME}
      LETSENCRYPT_HOST: ${DOMAIN_NAME}
      LETSENCRYPT_EMAIL: ${NOTIFICATION_EMAIL}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
networks:
  default:
    external:
      name: nginx-proxy